name: zotviewer
version: 2.2.0
summary: Zotero Visualizer
description: Your bibliography in your hands

confinement: strict
base: core22
grade: stable

slots:
  dbus-zotviewer:
    interface: dbus
    bus: session
    name: com.fvalle1.zotviewer
    
apps:
  zotviewer:
    command: zotviewer
    extensions: [gnome]
    plugs:
    - network
    slots:
      - dbus-zotviewer
parts:
  zotviewer:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
